pragma Singleton
import QtQuick

QtObject {
    property string background: "#fff5fafb"
    property string error: "#ffba1a1a"
    property string error_container: "#ffffdad6"
    property string inverse_on_surface: "#ffecf2f2"
    property string inverse_primary: "#ff81d3dd"
    property string inverse_surface: "#ff2b3132"
    property string on_background: "#ff161d1d"
    property string on_error: "#ffffffff"
    property string on_error_container: "#ff410002"
    property string on_primary: "#ffffffff"
    property string on_primary_container: "#ff001f23"
    property string on_primary_fixed: "#ff001f23"
    property string on_primary_fixed_variant: "#ff004f56"
    property string on_secondary: "#ffffffff"
    property string on_secondary_container: "#ff051f22"
    property string on_secondary_fixed: "#ff051f22"
    property string on_secondary_fixed_variant: "#ff324b4e"
    property string on_surface: "#ff161d1d"
    property string on_surface_variant: "#ff3f484a"
    property string on_tertiary: "#ffffffff"
    property string on_tertiary_container: "#ff0c1b36"
    property string on_tertiary_fixed: "#ff0c1b36"
    property string on_tertiary_fixed_variant: "#ff394764"
    property string outline: "#ff6f797a"
    property string outline_variant: "#ffbec8c9"
    property string primary: "#ff006971"
    property string primary_container: "#ff9df0fa"
    property string primary_fixed: "#ff9df0fa"
    property string primary_fixed_dim: "#ff81d3dd"
    property string scrim: "#ff000000"
    property string secondary: "#ff4a6366"
    property string secondary_container: "#ffcde7eb"
    property string secondary_fixed: "#ffcde7eb"
    property string secondary_fixed_dim: "#ffb1cbcf"
    property string shadow: "#ff000000"
    property string source_color: "#ff435b5e"
    property string surface: "#fff5fafb"
    property string surface_bright: "#fff5fafb"
    property string surface_container: "#ffe9eff0"
    property string surface_container_high: "#ffe3e9ea"
    property string surface_container_highest: "#ffdee4e4"
    property string surface_container_low: "#ffeff5f5"
    property string surface_container_lowest: "#ffffffff"
    property string surface_dim: "#ffd5dbdc"
    property string surface_tint: "#ff006971"
    property string surface_variant: "#ffdae4e5"
    property string tertiary: "#ff505e7d"
    property string tertiary_container: "#ffd8e2ff"
    property string tertiary_fixed: "#ffd8e2ff"
    property string tertiary_fixed_dim: "#ffb8c6ea"
}
