pragma Singleton
import QtQuick

QtObject {
    property string background: "#fffff8f6"
    property string error: "#ffba1a1a"
    property string error_container: "#ffffdad6"
    property string inverse_on_surface: "#ffffede7"
    property string inverse_primary: "#ffffb599"
    property string inverse_surface: "#ff392e2a"
    property string on_background: "#ff231a16"
    property string on_error: "#ffffffff"
    property string on_error_container: "#ff410002"
    property string on_primary: "#ffffffff"
    property string on_primary_container: "#ff370e00"
    property string on_primary_fixed: "#ff370e00"
    property string on_primary_fixed_variant: "#ff71361d"
    property string on_secondary: "#ffffffff"
    property string on_secondary_container: "#ff2c160d"
    property string on_secondary_fixed: "#ff2c160d"
    property string on_secondary_fixed_variant: "#ff5d4035"
    property string on_surface: "#ff231a16"
    property string on_surface_variant: "#ff53433e"
    property string on_tertiary: "#ffffffff"
    property string on_tertiary_container: "#ff211b00"
    property string on_tertiary_fixed: "#ff211b00"
    property string on_tertiary_fixed_variant: "#ff50471a"
    property string outline: "#ff85736d"
    property string outline_variant: "#ffd8c2bb"
    property string primary: "#ff8e4d32"
    property string primary_container: "#ffffdbce"
    property string primary_fixed: "#ffffdbce"
    property string primary_fixed_dim: "#ffffb599"
    property string scrim: "#ff000000"
    property string secondary: "#ff77574b"
    property string secondary_container: "#ffffdbce"
    property string secondary_fixed: "#ffffdbce"
    property string secondary_fixed_dim: "#ffe7beaf"
    property string shadow: "#ff000000"
    property string source_color: "#fff5d8ce"
    property string surface: "#fffff8f6"
    property string surface_bright: "#fffff8f6"
    property string surface_container: "#fffceae4"
    property string surface_container_high: "#fff6e4df"
    property string surface_container_highest: "#fff1dfd9"
    property string surface_container_low: "#fffff1ec"
    property string surface_container_lowest: "#ffffffff"
    property string surface_dim: "#ffe8d6d1"
    property string surface_tint: "#ff8e4d32"
    property string surface_variant: "#fff5ded6"
    property string tertiary: "#ff685e30"
    property string tertiary_container: "#fff1e3a8"
    property string tertiary_fixed: "#fff1e3a8"
    property string tertiary_fixed_dim: "#ffd4c78e"
}
